$finalNames =
	"s02e15 40 Aniversario de El Imperio Contraataca - The Empire Strikes Back 40th Anniversary",
	"s01e26 Al rescate de Han - Leia and Han - The Han Rescue",
	"s01e32 Amistad inesperada de Chewbacca - Chewie and Ewoks - Hijacking a Walker",
	"s02e11 Batalla en Hoth - Battle of Hoth",
	"s01e34 Boba Fett, el cazarrecompensas - Boba Fett - The Bounty Hunter",
	"s01e05 Chewbacca El copiloto de confianza - Chewbacca - The Trusty Co-Pilot",
	"s01e37 Chewbacca Fiel companero - Han and Chewie - A Lifelong Partnership",
	"s01e30 Chewbacca Guerrero Wookiee - Chewbacca - Wookiee Warrior",
	"s01e10 Chewie vs Holoajedrez - Chewie vs. Holochess – Let The Wookiee Win",
	"s02e13 Cita en Bespin - Rendezvous at Bespin",
	"s01e06 Darth Vader El poder del Imperio - Darth Vader - Might of the Empire",
	"s01e02 Darth Vader El Poder del Lado Oscuro - Darth Vader - Power of the Dark Side",
	"s01e22 Darth Vader Piloto de caza - Darth Vader vs. the Rebel Fleet - Fearsome Fighter Pilot",
	"s01e29 Darth Vader vs Rebeldes de Hoth - Darth Vader vs. Hoth Rebels - Crushing the Rebellion",
	"s01e31 El combate de Luke - Luke vs. the Rancor - Wrath of the Rancor",
	"s02e14 Enfrentamiento en Ciudad Nube - Clash on Cloud City",
	"s01e18 Han Solo Alzando el vuelo por sus amigos - Han Solo - Taking Flight for his Friends",
	"s01e20 Han Solo Buscando a Yoda - Yoda - The Jedi Master",
	"s01e09 Han Solo El mejor contrabandista - Han Solo - Galaxy’s Best Smuggler",
	"s01e23 Han Solo Escapando de la cueva - Han Solo vs. the Space Slug - The Escape Artist",
	"s01e33 Han Solo, un lider - Han Solo - From Smuggler to General",
	"s01e27 Jabba el Hutt Gangster Galactico - Jabba the Hutt - Galactic Gangster",
	"s02e08 Kylo Ren vs los Rebeldes de la Resistencia - Kylo Ren vs. Resistance Rebels",
	"s02e03 Kylo Ren y Darth Vader - Un legado de poder - Kylo Ren and Darth Vader - A Legacy of Power",
	"s01e36 La emboscada de los ewoks - Ewoks vs. The Empire - Small but Mighty",
	"s02e01 La Fuerza llama a Rey - The Force Calls to Rey",
	"s02e10 La Primera Orden contra la Resistencia - The First Order vs. The Resistance",
	"s01e07 La Princesa Leia vs Darth Vader - Princess Leia vs. Darth Vader - A Fearless Leader",
	"s01e35 La profecia - Jedi vs. Sith - The Skywalker Saga",
	"s02e04 Leia Organa - Una Princesa, una General - Leia Organa - A Princess, A General, A Mentor",
	"s02e07 Los droides de Star Wars - Star Wars Droids",
	"s01e16 Luke Entrenamiento de espada laser - Luke Skywalker - Lightsaber Training",
	"s01e01 Luke Skywalker El viaje comienza - Luke Skywalker - The Journey Begins",
	"s01e21 Luke Skywalker vs Caminantes Imperiales - Luke vs. Imperial Walkers - Commander on Hoth",
	"s01e12 Luke Skywalker vs Darth Vader - Luke Skywalker vs. Darth Vader – Join Me",
	"s01e11 Luke vs El Emperador Palpatine - Luke vs. Emperor Palpatine – Rise to Evil",
	"s01e03 Luke vs el Wampa Escape de la Caverna - Luke vs. the Wampa - Cavern Escape",
	"s01e28 Luke vs Jabba Fuga de la barcaza velera - Luke vs. Jabba - Sail Barge Escape",
	"s01e08 Luke vs la Estrella de la Muerte - Luke vs. the Death Star – X-wing Assault",
	"s01e14 Princesa Leia El Rescate - Princess Leia - The Rescue",
	"s01e25 Princesa Leia Un amigo inesperado - Princess Leia - An Unexpected Friend",
	"s01e24 R2-D2 El Mejor Amigo De Un Piloto - R2-D2 - A Pilot's Best Friend",
	"s01e04 R2-D2 Un droide leal - R2-D2 - A Loyal Droid",
	"s01e19 R2-D2 y C-3PO - R2-D2 and C3PO - Trash Compactor Rescue",
	"s02e06 Rey e Finn vs Kylo Ren - Rey and Finn vs. Kylo Ren",
	"s02e02 Rey y sus amigos contra la Primera Orden - Rey and Friends vs. The First Order",
	"s02e09 Una amistad sin igual - An Unlikely Friendship",
	"s02e12 Viaje a Dagobah - Journey to Dagobah",
	"s01e13 Yoda La altura no importa - Yoda vs. Count Dooku - Size Matters Not"

$filesEng =
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e15 - The Empire Strikes Back 40th Anniversary.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e26 - Leia and Han - The Han Rescue.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e32 - Chewie and Ewoks - Hijacking a Walker.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e11 - Battle of Hoth.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e34 - Boba Fett - The Bounty Hunter.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e05 - Chewbacca - The Trusty Co-Pilot.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e37 - Han and Chewie - A Lifelong Partnership.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e30 - Chewbacca - Wookiee Warrior.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e10 - Chewie vs. Holochess – Let The Wookiee Win.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e13 - Rendezvous at Bespin.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e06 - Darth Vader - Might of the Empire.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e02 - Darth Vader - Power of the Dark Side.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e22 - Darth Vader vs. the Rebel Fleet - Fearsome Fighter Pilot.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e29 - Darth Vader vs. Hoth Rebels - Crushing the Rebellion.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e31 - Luke vs. the Rancor - Wrath of the Rancor.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e14 - Clash on Cloud City.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e18 - Han Solo - Taking Flight for his Friends.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e20 - Yoda - The Jedi Master.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e09 - Han Solo - Galaxy’s Best Smuggler.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e23 - Han Solo vs. the Space Slug - The Escape Artist.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e33 - Han Solo - From Smuggler to General.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e27 - Jabba the Hutt - Galactic Gangster.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e08 - Kylo Ren vs. Resistance Rebels.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e03 - Kylo Ren and Darth Vader - A Legacy of Power.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e36 - Ewoks vs. The Empire - Small but Mighty.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e01 - The Force Calls to Rey.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e10 - The First Order vs. The Resistance.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e07 - Princess Leia vs. Darth Vader - A Fearless Leader.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e35 - Jedi vs. Sith - The Skywalker Saga.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e04 - Leia Organa - A Princess, A General, A Mentor.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e07 - Star Wars Droids.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e16 - Luke Skywalker - Lightsaber Training.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e01 - Luke Skywalker - The Journey Begins.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e21 - Luke vs. Imperial Walkers - Commander on Hoth.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e12 - Luke Skywalker vs. Darth Vader – Join Me.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e11 - Luke vs. Emperor Palpatine – Rise to Evil.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e03 - Luke vs. the Wampa - Cavern Escape.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e28 - Luke vs. Jabba - Sail Barge Escape.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e08 - Luke vs. the Death Star – X-wing Assault.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e14 - Princess Leia - The Rescue.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e25 - Princess Leia - An Unexpected Friend.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e24 - R2-D2 - A Pilot's Best Friend.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e04 - R2-D2 - A Loyal Droid.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e19 - R2-D2 and C3PO - Trash Compactor Rescue.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e06 - Rey and Finn vs. Kylo Ren.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e02 - Rey and Friends vs. The First Order.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e09 - An Unlikely Friendship.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 02\s02e12 - Journey to Dagobah.mp4",
	"E:\films\series\Star Wars Galaxy of Adventures\season 01\s01e13 - Yoda vs. Count Dooku - Size Matters Not.mp4"

$filesSpa =
	"D:\Star Wars Galaxy of Adventures Español\40 Aniversario de El Imperio Contraataca.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Al rescate de Han.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Amistad inesperada de Chewbacca.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Batalla en Hoth.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Boba Fett, el cazarrecompensas.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Chewbacca El copiloto de confianza.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Chewbacca Fiel companero.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Chewbacca Guerrero Wookiee.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Chewie vs Holoajedrez.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Cita en Bespin.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Darth Vader El poder del Imperio.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Darth Vader El Poder del Lado Oscuro.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Darth Vader Piloto de caza.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Darth Vader vs Rebeldes de Hoth.mp4",
	"D:\Star Wars Galaxy of Adventures Español\El combate de Luke.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Enfrentamiento en Ciudad Nube.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Han Solo Alzando el vuelo por sus amigos.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Han Solo Buscando a Yoda.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Han Solo El mejor contrabandista.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Han Solo Escapando de la cueva.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Han Solo, un lider.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Jabba el Hutt Gangster Galactico.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Kylo Ren vs los Rebeldes de la Resistencia.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Kylo Ren y Darth Vader - Un legado de poder.mp4",
	"D:\Star Wars Galaxy of Adventures Español\La emboscada de los ewoks.mp4",
	"D:\Star Wars Galaxy of Adventures Español\La Fuerza llama a Rey.mp4",
	"D:\Star Wars Galaxy of Adventures Español\La Primera Orden contra la Resistencia.mp4",
	"D:\Star Wars Galaxy of Adventures Español\La Princesa Leia vs Darth Vader.mp4",
	"D:\Star Wars Galaxy of Adventures Español\La profecia.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Leia Organa - Una Princesa, una General.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Los droides de Star Wars.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Luke Entrenamiento de espada laser.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Luke Skywalker El viaje comienza.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Luke Skywalker vs Caminantes Imperiales.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Luke Skywalker vs Darth Vader.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Luke vs El Emperador Palpatine.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Luke vs el Wampa Escape de la Caverna.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Luke vs Jabba Fuga de la barcaza velera.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Luke vs la Estrella de la Muerte.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Princesa Leia El Rescate.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Princesa Leia Un amigo inesperado.mp4",
	"D:\Star Wars Galaxy of Adventures Español\R2-D2 El Mejor Amigo De Un Piloto.mp4",
	"D:\Star Wars Galaxy of Adventures Español\R2-D2 Un droide leal.mp4",
	"D:\Star Wars Galaxy of Adventures Español\R2-D2 y C-3PO.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Rey e Finn vs Kylo Ren.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Rey y sus amigos contra la Primera Orden.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Una amistad sin igual.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Viaje a Dagobah.mp4",
	"D:\Star Wars Galaxy of Adventures Español\Yoda La altura no importa.mp4"

$destineFolder = "D:\Star Wars Galaxy of Adventures"

for ($i = 0; $i -lt $finalNames.Count; $i++) {
	mkvmerge --output "$(Join-Path $destineFolder $finalNames[$i]).mkv" --title $finalNames[$i] --language 1:eng $filesEng[$i] --language 1:spa -D $filesSpa[$i] --track-order 0:0,1:1,0:1
	if ($LASTEXITCODE -ne 0) { $errors = $errors, $finalNames[$i] }
}

Write-Warning "Errors in: $errors"